project:
  type: website
  resources:
    - data/dataset/timesfm_3days.csv
    - data/dataset/thane.csv

website:
  title: "Delhi Air Quality"
  navbar:
    left:
      - text: Station Level PM₂.₅ Forecasting
        href: forecasting.qmd
      - text: Spatial Interpolation
        href: interpolation.qmd
      - text: Thane Forecasting
        href: thane.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
